### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by nikparth** [shoaibahmed/blockwise_ssl#1]
Hi I'm very interested in this as I'm working on related topics and I'd like to compare your pretrained models to some I've trained. Would it be possible for you to send the best blockwise Barlow and SimCLR model you've trained? 

Thanks! 
Nikhil

**Comment by shoaibahmed** [comment]
Hi Nikhil,

Thank you for your interest in our work. I have updated the README to include a link to our pretrained ***1x1 CbE + GSP*** model. 

Please do let me know in case you need anything else from our side.

Best regards,
Shoaib

**Comment by nikparth** [comment]
Great thanks! Do you mind uploading the same model but trained with the SimCLR objective also if possible (since I believe you mentioned in the paper that you trained with both Barlow and SimCLR)? I'd like to do a comparison across the two objectives, but if that is not possible then no worries. 

Thanks!
Nikhil

**Comment by shoaibahmed** [comment]
Sadly, we are unable to retrieve many of our checkpoints due to storage issues. Rerunning those experiments is the only way to get those checkpoints right now.

**Comment by nikparth** [comment]
ok thank you!
