### ISSUE TITLE
About the running time

### ISSUE THREAD

**Issue by Big-Brother-Pikachu** [shoaibahmed/blockwise_ssl#2]
Hi, thanks for sharing this wonderful work. We have tried to run your codes on our 2 A800 GPUs, but have found that we need 1300~ hours to finish the 300 epochs ImageNet experiment. Is it normal? Or could you tell us approximately how long it takes for you to conduct an experiment? This will be of great help to us. Thank you!

**Comment by shoaibahmed** [comment]
Hi,
Thanks for your interest. Some of the models we trained took about a week on 32 A6000s. We chose such a long training schedule to match the training scheme used in prior work such as Barlow Twins.

**Comment by Big-Brother-Pikachu** [comment]
OK, I get it! Thanks for your reply!
